// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Pongo.BusinessLogic;
using System;

namespace Pongo.BusinessLogic.Migrations
{
    [DbContext(typeof(PongoContext))]
    [Migration("20171105001013_Migration4")]
    partial class Migration4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pongo.BusinessLogic.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("RowId");

                    b.Property<int?>("RowId1");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8000);

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("RowId1");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Required");

                    b.Property<int?>("TableId");

                    b.Property<int?>("TableId1");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("TableId1");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("TableId");

                    b.Property<int?>("TableId1");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("TableId1");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Cell", b =>
                {
                    b.HasOne("Pongo.BusinessLogic.Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId");

                    b.HasOne("Pongo.BusinessLogic.Row")
                        .WithMany()
                        .HasForeignKey("RowId1");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Column", b =>
                {
                    b.HasOne("Pongo.BusinessLogic.Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId");

                    b.HasOne("Pongo.BusinessLogic.Table")
                        .WithMany()
                        .HasForeignKey("TableId1");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Row", b =>
                {
                    b.HasOne("Pongo.BusinessLogic.Table")
                        .WithMany("Rows")
                        .HasForeignKey("TableId");

                    b.HasOne("Pongo.BusinessLogic.Table")
                        .WithMany()
                        .HasForeignKey("TableId1");
                });

            modelBuilder.Entity("Pongo.BusinessLogic.Table", b =>
                {
                    b.HasOne("Pongo.BusinessLogic.User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
